# Generated by Django 5.0.1 on 2024-01-16 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(choices=[(1, 'Branco'), (2, 'Preto'), (3, 'Amarelo'), (4, 'Tricolor'), (5, 'Branco e Preto')], max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age_type', models.CharField(choices=[(1, 'Dias'), (2, 'Meses'), (3, 'Anos')], default=1, max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[(1, 'Pequeno'), (2, 'Médio'), (3, 'Grande')], max_length=30)),
            ],
        ),
    ]
