# Generated by Django 5.0.1 on 2024-01-16 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 15, 30, 17, 868615, tzinfo=datetime.timezone.utc)),
        ),
    ]
