# Generated by Django 5.0.1 on 2024-01-16 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_pet_size_alter_pet_age_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Amarelo', 'Amarelo'), ('Tricolor', 'Tricolor'), ('Branco e Amarelo', 'Branco e Amarelo'), ('Preto e Branco', 'Preto e Branco')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 19, 26, 50, 780739, tzinfo=datetime.timezone.utc)),
        ),
    ]
