# Generated by Django 5.0.1 on 2024-01-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_pet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro'), ('Hamster', 'Hamster'), ('Coelho', 'Coelho'), ('Pássaro', 'Pássaro')], default='Gato', max_length=8),
        ),
        migrations.AlterField(
            model_name='pet',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Amarelo', 'Amarelo'), ('Tricolor', 'Tricolor'), ('Branco e Amarelo', 'Branco e Yellow'), ('Preto e Branco', 'Preto e Branco')], default='Branco', max_length=16),
        ),
    ]
