# Generated by Django 5.0.1 on 2024-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_pet_animal_type_alter_pet_available_alter_pet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pet_imgs/%Y'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('days', 'Dias'), ('months', 'Meses'), ('years', 'Anos')], default='days', max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('cat', 'Gato'), ('dog', 'Cachorro'), ('hamster', 'Hamster'), ('rabbit', 'Coelho'), ('bird', 'Pássaro')], default='cat', max_length=8),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('white', 'Branco'), ('black', 'Preto'), ('yellow', 'Amarelo'), ('tricolor', 'Tricolor'), ('white_yellow', 'Branco e Amarelo'), ('black_white', 'Preto e Branco')], default='white', max_length=16),
        ),
    ]
