# Generated by Django 5.0.1 on 2024-01-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_remove_pet_picture_petimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petimages',
            options={'verbose_name_plural': 'Pet Images'},
        ),
    ]
